import type { Metadata } from "next";
import { ArrowLeftIcon } from "@phosphor-icons/react/dist/ssr/ArrowLeft";
import { BrandMark } from "../components/BrandMark";

export const metadata: Metadata = {
  title: "Terms of Use · AfterMeet",
  description: "The terms that govern your use of AfterMeet.",
};

const LAST_UPDATED = "August 10, 2026";

export default function TermsPage() {
  return (
    <main className="mx-auto w-full max-w-[760px] px-6 py-16 text-[#163300]">
      <a href="/" className="mb-10 inline-flex items-center gap-2 text-sm font-bold text-[#163300] hover:text-[#0e0f0c]">
        <ArrowLeftIcon size={15} weight="bold" />
        AfterMeet
      </a>
      <div className="mb-10 flex items-center gap-3">
        <BrandMark size={36} />
        <div>
          <h1 className="text-3xl font-black tracking-tight sm:text-4xl">Terms of Use</h1>
          <p className="mt-1 text-sm text-[#454745]">Last updated {LAST_UPDATED}</p>
        </div>
      </div>

      <div className="space-y-10 text-[15px] leading-relaxed text-[#163300]">
        <section>
          <p>
            These terms govern your use of AfterMeet. By creating an account or using the product, you agree
            to them. If you&apos;re using AfterMeet on behalf of an organization, you&apos;re agreeing on its
            behalf and confirming you have the authority to do so.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold tracking-tight">The service</h2>
          <p>
            AfterMeet helps you capture people you meet, record context from those meetings, and turn that
            into follow-ups and event tracking. Some features are AI-assisted (note summarization, follow-up
            drafting) &mdash; you review and approve AI-generated content before it&apos;s sent or acted on.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold tracking-tight">Your account</h2>
          <ul className="list-disc space-y-2 pl-5">
            <li>You&apos;re responsible for the accuracy of the information you add and for keeping your account credentials secure.</li>
            <li>You must be legally able to enter into these terms and old enough to use the service under applicable law.</li>
            <li>You&apos;re responsible for having a lawful basis (such as consent or legitimate interest, where required) to record notes about, and follow up with, the people you capture.</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold tracking-tight">Connected accounts (Google, Microsoft)</h2>
          <p>
            If you connect a Google or Microsoft account, you authorize AfterMeet to act within the specific
            scopes you grant &mdash; sending an email only when you approve a draft, reading calendar events to
            suggest and link events, and creating files only within an app-scoped folder. You can revoke this
            access at any time from Settings, and doing so stops AfterMeet from making further requests to that
            account. See our <a className="font-bold underline" href="/privacy">Privacy Policy</a> for details
            on how this data is used.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold tracking-tight">Acceptable use</h2>
          <p>You agree not to:</p>
          <ul className="list-disc space-y-2 pl-5">
            <li>Use AfterMeet to send spam, unsolicited bulk email, or harassing messages.</li>
            <li>Attempt to access another user&apos;s account or data without authorization.</li>
            <li>Reverse engineer, scrape, or interfere with the operation of the service.</li>
            <li>Use the service in a way that violates applicable law, including data protection law.</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold tracking-tight">AI-generated content</h2>
          <p>
            Summaries, follow-up drafts, and event suggestions are generated by AI models and may be
            inaccurate or incomplete. You&apos;re responsible for reviewing this content before relying on it
            or sending it to someone else.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold tracking-tight">Service availability</h2>
          <p>
            AfterMeet is provided &ldquo;as is&rdquo; while we build and improve it. We don&apos;t guarantee
            uninterrupted availability and may change or discontinue features. We&apos;ll do our best to give
            notice of material changes that affect your data.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold tracking-tight">Termination</h2>
          <p>
            You can stop using AfterMeet and delete your account at any time from Settings. We may suspend or
            terminate accounts that violate these terms.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold tracking-tight">Contact us</h2>
          <p>
            Questions about these terms can be sent to{" "}
            <a className="font-bold underline" href="mailto:rafreo21@gmail.com">rafreo21@gmail.com</a>.
          </p>
        </section>
      </div>
    </main>
  );
}
