plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.ehllo.app.audiosegmentstitcher'
version = '0.1.0'

android {
  namespace "com.ehllo.app.audiosegmentstitcher"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}
